### ISSUE TITLE
Mention this isn't an official tool

### ISSUE THREAD

**Issue by jcs** [aaronfagan/pushover-cli#19]
Please make it clear in your documentation that this is not an official Pushover tool.  Thanks.

https://pushover.net/press/logos

**Comment by aaronfagan** [comment]
Will do.

Will add mention in the README that this tool, nor its author are affiliated in anyway with Pushover, or the company that owns it.

Will that suffice? By the way, great service!

**Comment by aaronfagan** [comment]
Hey again, I’ve added a blurb to the readme: 
https://github.com/aaronfagan/pushover-cli/blob/master/README.md

Please advise if this is sufficient. Thanks!
