### ISSUE TITLE
Feature Request: Quiet Mode (No Output)

### ISSUE THREAD

**Issue by tjharman** [aaronfagan/pushover-cli#46]
Hi,

I'd love it if it was possible to say pushover --quiet --message "Blah" and the only way I knew if it passed/failed was from the return value.
This makes using it in cron etc much easier, I don't have to see the "> Sending notification...success!" messages in the cron output.

Thanks!

**Comment by aaronfagan** [comment]
I’ll look into that for you 🙂

**Comment by aaronfagan** [comment]
@tjharman:

Quiet mode has been added. Use `--quiet` or `-q` to silence all output.

Upgrade to the latest version with `pushover --upgrade` to enable this functionality. While I have tested this extensively, please open a new ticket if you encounter any issues!

Thanks!

**Comment by tjharman** [comment]
Can't believe I never came back and said thanks.
So nearly 7 years later, thanks very much for adding this
(yes I still use this script all the time)
